name: Auto Deploy and Restart Nginx

on:
  push:
    branches:
      - '**' # trigger on push to any branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest changes
        run: |
          git pull

      - name: Restart Nginx
        run: sudo systemctl restart nginx
